# web访问端口号 约定：8088  -Dserver.port=8088
server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    url: jdbc:mysql://42.194.178.153:3306/foodie_shop?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=false
    username: foodie_shop
    password: 123456
  hikari:
    connection-timeout: 60000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
    minimum-idle: 5 # 最小连接数
    maximum-pool-size: 20 # 最大连接数
    auto-commit: true # 自动提交
    idle-timeout: 60000 # 连接超时的最大时长（毫秒），超时则被释放（retired）
    pool-name: DateSourceHikariCP # 连接池名字
    max-lifetime: 60000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired）
    validation-timeout: 3000
    connection-test-query: SELECT 1

# 配置Mybatis log，使用mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 配置控制台输出sql
  type-aliases-package: com.imooc.pojo                      # POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml                  # mapper映射文件